name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Clean bucket
        run: aws s3 rm  ${{secrets.AWS_S3_BUCKET}} --recursive

      - name: Upload
        run: aws s3 cp dist ${{secrets.AWS_S3_BUCKET}} --recursive;
